currency_pairs:
  - "BTCARS"
  - "BTCUSDT"

notable_events:
  "2023-08-13 23:00:00-03:00": "Primary election victory for Javier Milei"
  "2023-10-22 21:00:00-03:00": "General election victory"
  "2023-12-21 15:30:00-03:00": "Finance minister's tweet about Bitcoin approval"