currency_pairs:
  - "BTCARS"
  - "BTCUSDT"

notable_events:
  "2023-08-11 09:30:00-04:00": "US stock market opens (Friday)"
  "2023-08-13 23:00:00-03:00": "Primary election victory for Javier Milei (Sunday)"
  "2023-08-14 09:30:00-04:00": "US stock market opens (Monday)"
  "2023-10-20 09:30:00-04:00": "US stock market opens (Friday)"
  "2023-10-22 21:00:00-03:00": "General election victory (Sunday)"
  "2023-10-23 09:30:00-04:00": "US stock market opens (Monday)"
  "2023-12-20 09:30:00-04:00": "US stock market opens (Wednesday)"
  "2023-12-21 15:30:00-03:00": "Finance minister's tweet about Bitcoin approval (Thursday)"
  "2023-12-22 09:30:00-04:00": "US stock market opens (Friday)"
